RFAdvice: coercion issue
BW-5492
http://makerbot.atlassian.net/browse/BW-5492

Took in advice from multiple online sources re: how to attach Qt EventFilters to QML, primarily from:

    https://stackoverflow.com/questions/38698604/how-to-install-and-use-an-event-filter-written-in-qt-c-in-a-qml-application

As well as singleton implementation guidelines from:

    https://stackoverflow.com/questions/1008019/c-singleton-design-pattern

Currently, the singleton GetInstance prototype is written to be compatible with the main.cpp::qmlRegisterSingletonType() call's required parameters, but runs afoul of the instantiation as a "plain" QObject:
    error: cannot dynamic_cast 'UiEventLogger::GetInstance' (of type 'class QObject* (*)(class QQmlEngine*, class QJSEngine*)') to type 'class QObject' (target is not pointer or reference)