INCOMPLETE- add date & time display to top bar
BW-5495
http://makerbot.atlassian.net/browse/BW-5495

INCOMPLETE - has issues:
[] needs refinement in text positioning
[] bot.getSystemTime() needs to be called ~10x per second for the appearance of a time passage
    indicator's blinking to be "balanced", but each call currently spams kaiten.log on every
    update with:
>
>     systemtime.py:103: ERROR
>     kaiten.systemtime.SystemTime:_get_rtc_time
>     2021-09-09 15:18:10,798
>     RTC date must be set before get: [Errno 22] Invalid argument